// Common daemons.
export const DAEMON_DATAMINE_V1 = 'DAEMON_DATAMINE_V1';
export const DAEMON_DATAMINE_V2 = 'DAEMON_DATAMINE_V2';
export const DAEMON_DATAMINE_V3 = 'DAEMON_DATAMINE_V3';
export const DAEMON_ICEPICK = 'DAEMON_ICEPICK';
// Perk daemons.
export const DAEMON_MASS_VULNERABILITY = 'DAEMON_MASS_VULNERABILITY';
export const DAEMON_CAMERA_SHUTDOWN = 'DAEMON_CAMERA_SHUTDOWN';
export const DAEMON_FRIENDLY_TURRETS = 'DAEMON_FRIENDLY_TURRETS';
export const DAEMON_TURRET_SHUTDOWN = 'DAEMON_TURRET_SHUTDOWN';
// Passive from legendary daemons.
export const DAEMON_OPTICS_JAMMER = 'DAEMON_OPTICS_JAMMER';
export const DAEMON_WEAPONS_JAMMER = 'DAEMON_WEAPONS_JAMMER';
// Quest or special daemons.
export const DAEMON_DATAMINE_COPY_MALWARE = 'DAEMON_DATAMINE_COPY_MALWARE';
export const DAEMON_NEUTRALIZE_MALWARE = 'DAEMON_NEUTRALIZE_MALWARE';
export const DAEMON_GAIN_ACCESS = 'DAEMON_GAIN_ACCESS';
export const DAEMON_DATAMINE_CRAFTING_SPECS = 'DAEMON_DATAMINE_CRAFTING_SPECS';
