name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-2019]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
          build_script_name: webpack:build
